FROM node:18-alpine as build
WORKDIR /app
COPY ./ ./
RUN npm install
RUN npm run build

FROM nginx:1.21-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY --from=build /app/nginx.conf /etc/nginx/conf.d/default.conf
